preferred_provider: qdrant_cloud


retrieval_endpoints:
  qdrant_cloud:
    enabled: true
    api_endpoint_env: QDRANT_URL
    api_key_env: QDRANT_API_KEY
    embedding_provider: gemini
    index_name: skus
    db_type: qdrant

providers:
  gemini:
    api_key_env: GEMINI_API_KEY
    model: models/text-embedding-004
