preferred_endpoint: qdrant_cloud

retrieval_endpoints:
  qdrant_cloud:
    endpoint_type: qdrant
    api_key_env_var: QDRANT_API_KEY
    url_env_var: QDRANT_URL
    collection_name: nlweb_tink
    embedding_model: text-embedding-3-small
    embedding_dimension: 1536
